# Generated by Django 5.2.3 on 2025-06-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_approval_date_video_approval_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_public',
        ),
    ]
