# Generated by Django 5.2.3 on 2025-06-30 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_submission_terms_accepted_and_more'),
        ('videos', '0004_remove_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_standalone',
            field=models.BooleanField(default=False, help_text='Whether this is a standalone video not associated with any contest'),
        ),
        migrations.AlterField(
            model_name='video',
            name='contest',
            field=models.ForeignKey(blank=True, help_text='Optional: The contest this video is submitted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='video',
            name='submission',
            field=models.OneToOneField(blank=True, help_text='Optional: The submission this video is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='contests.submission'),
        ),
    ]
