# Generated by Django 5.2.3 on 2025-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_creator_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Profile banner image', upload_to='creator_banners/'),
        ),
    ]
