# Generated by Django 5.2.3 on 2025-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_brandprofile_bio_brandprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='company_type',
            field=models.CharField(choices=[('corporation', 'Corporation'), ('llc', 'Limited Liability Company'), ('partnership', 'Partnership'), ('sole_proprietorship', 'Sole Proprietorship'), ('nonprofit', 'Non-Profit Organization'), ('other', 'Other')], default='corporation', help_text='Type of company', max_length=50),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Name of primary contact person', max_length=100),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Complete physical address', max_length=500),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Company description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo', upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='industry_type',
            field=models.CharField(blank=True, help_text='Industry sector', max_length=100),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Company website'),
        ),
    ]
