# Generated by Django 5.2.3 on 2025-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_brandprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='receive_sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications for new contests and updates'),
        ),
    ]
