# Generated by Django 5.2.3 on 2025-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_creatorprofile_receive_sms_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='shipping_address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2 (Optional)'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP/Postal Code'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State/Province/Region'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='company_type',
            field=models.CharField(choices=[('Media Company', 'Media Company'), ('Modeling Agency', 'Modeling Agency'), ('Production Company', 'Production Company'), ('Non-Profit Organization', 'Non-Profit Organization'), ('Other', 'Other')], default='corporation', help_text='Type of company', max_length=50),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Your physical address (Legacy field)', max_length=500),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Country (Legacy field)', max_length=100),
        ),
    ]
