# Generated by Django 5.2.3 on 2025-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_creatorprofile_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_address_line1',
            field=models.CharField(help_text='Street address, P.O. box, company name, c/o', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_address_line2',
            field=models.CharField(help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True, verbose_name='Address Line 2 (Optional)'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_city',
            field=models.CharField(help_text='City or town', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_country',
            field=models.CharField(help_text='Country', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_postal_code',
            field=models.CharField(help_text='Postal code or ZIP code', max_length=20, verbose_name='ZIP/Postal Code'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_state',
            field=models.CharField(help_text='State, province, or region', max_length=100, verbose_name='State/Province/Region'),
        ),
    ]
