# Generated by Django 5.2.3 on 2025-07-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('all_picked', 'All Picked'), ('archived', 'Archived')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
