# Generated by Django 5.2.3 on 2025-07-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_product_status'),
        ('contests', '0006_contestapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='contests.contest', verbose_name='Contest'),
        ),
    ]
