# Generated by Django 5.2.3 on 2025-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='specialties',
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy address field (deprecated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='shipping_address_line2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True, verbose_name='Address Line 2 (Optional)'),
        ),
    ]
