# Generated by Django 5.2.3 on 2025-07-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_creatorprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Content Creator'), ('brand', 'Brand/Company'), ('admin', 'Admin')], default='creator', max_length=20),
        ),
    ]
