# Generated by Django 5.2.3 on 2025-07-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_creatorprofile_profile_picture_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='creator_profiles/'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', verbose_name='YouTube'),
        ),
    ]
