# Generated by Django 5.2.3 on 2025-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_contest', 'New Contest Available'), ('contest_closed', 'Contest Closed'), ('winner_chosen', 'Winner Chosen'), ('new_submission', 'New Submission'), ('submission_feedback', 'Submission Feedback'), ('application_approved', 'Contest Application Approved'), ('application_rejected', 'Contest Application Rejected')], max_length=50),
        ),
    ]
