# Generated by Django 5.1.3 on 2025-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='contest_thumbnails/'),
        ),
        migrations.AddField(
            model_name='contest',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
