# Generated by Django 5.1.3 on 2025-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_is_featured_contest_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rules',
            field=models.TextField(blank=True, help_text='Contest rules and guidelines'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='brief',
            field=models.TextField(help_text='Brief description of what you want'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='inspiration',
            field=models.TextField(blank=True, help_text='Examples or inspiration for creators'),
        ),
    ]
