# Generated by Django 5.2.3 on 2025-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_rules_alter_contest_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
