# Generated by Django 5.2.3 on 2025-07-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_contestapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestapplication',
            name='contest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='contests.contest'),
        ),
    ]
